### ISSUE TITLE
Set Visibility dynamically of menu item  crashes the app

### ISSUE THREAD

**Issue by k-farhan** [ittianyu/BottomNavigationViewEx#155]
Hey, thank you for the awesome work 👍 .

I am having problem while try to set the visibility of menu item.

This is how I tried to set the visibility.
``` 
private void showMainMenuItem() {
    if (someConditionMatched) {
        getScanMenuItem().setVisible(true);
    }
}

private MenuItem getScanMenuItem() {
    return bottomNavigationView.getMenu().findItem(R.id.action_main_menu_item);
}
```

and the crash is below

```2019-02-01 17:59:25.773 17711-17711/com.myawesomeapp.duck.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myawesomeapp.duck.debug, PID: 17711
    java.lang.IllegalArgumentException: Cannot set 'scaleX' to Float.NaN
        at android.view.View.sanitizeFloatPropertyValue(View.java:15445)
        at android.view.View.sanitizeFloatPropertyValue(View.java:15419)
        at android.view.View.setScaleX(View.java:14808)
        at android.support.design.internal.BottomNavigationItemView.setViewValues(BottomNavigationItemView.java:245)
        at android.support.design.internal.BottomNavigationItemView.setChecked(BottomNavigationItemView.java:212)
        at android.support.design.internal.BottomNavigationItemView.initialize(BottomNavigationItemView.java:103)
        at android.support.design.internal.BottomNavigationMenuView.buildMenuView(BottomNavigationMenuView.java:523)
        at android.support.design.internal.BottomNavigationPresenter.updateMenuView(BottomNavigationPresenter.java:62)
        at android.support.v7.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:298)
        at android.support.v7.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1069)
        at android.support.v7.view.menu.MenuBuilder.onItemVisibleChanged(MenuBuilder.java:1108)
        at android.support.v7.view.menu.MenuItemImpl.setVisible(MenuItemImpl.java:665)
        at com.myawesomeapp.duck.ui.home.HomeActivity.showMainMenuItem(HomeActivity.java:557)
        at com.myawesomeapp.duck.ui.home.HomeActivity.onStart(HomeActivity.java:201)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7165)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2976)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1817)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6723)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
Can you please help me here so that I can set the visibility of item dynamically?
Thank you

**Comment by JichunMa** [comment]
add bottomNavigationView.setTextSize(0.1f);
 before  getScanMenuItem().setVisible(true);


The reason is in the method BottomNavigationViewInner#setTextVisibility inner  

> mLargeLabel.setTextSize(TypedValue.COMPLEX_UNIT_PX, 0);
> mSmallLabel.setTextSize(TypedValue.COMPLEX_UNIT_PX, 0);

but so sad the zero is hard write to the code. We can only call method **setTextSize(0.1f);** dynamically
