### ISSUE TITLE
The following classes could not be instantiated: - com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx

### ISSUE THREAD

**Issue by rakeshhotker** [ittianyu/BottomNavigationViewEx#206]
java.lang.IllegalArgumentException: Motion easing theme attribute must be a string
	at com.google.android.material.motion.MotionUtils.resolveThemeInterpolator(MotionUtils.java:59)
	at com.google.android.material.navigation.NavigationBarMenuView.<init>(NavigationBarMenuView.java:122)
	at com.google.android.material.bottomnavigation.BottomNavigationMenuView.<init>(BottomNavigationMenuView.java:48)
	at com.google.android.material.bottomnavigation.BottomNavigationView.createNavigationBarMenuView(BottomNavigationView.java:215)
	at com.google.android.material.navigation.NavigationBarView.<init>(NavigationBarView.java:162)
	at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:108)
	at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:103)
	at com.ittianyu.bottomnavigationviewex.BottomNavigationViewInner.<init>(BottomNavigationViewInner.java:65)
	at com.ittianyu.bottomnavigationviewex.BottomNavigationViewInner.<init>(BottomNavigationViewInner.java:61)
	at com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx.<init>(BottomNavigationViewEx.java:21)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:399)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:189)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:147)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:303)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:417)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:428)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:332)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1121)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1095)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1124)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1095)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:654)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:499)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:353)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:431)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:141)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:714)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$7(RenderTask.java:870)
	at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$2.run(RenderExecutor.kt:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by rakeshhotker** [comment]
![Screenshot from 2022-01-26 21-32-07](https://user-images.githubusercontent.com/55056403/151199706-ff6766a5-ef00-4db3-a350-39405b5e952a.png)
![Screenshot from 2022-01-26 21-32-13](https://user-images.githubusercontent.com/55056403/151199713-145738f7-6372-4f3e-860f-8ee41767d86f.png)
![Screenshot from 2022-01-26 21-34-30](https://user-images.githubusercontent.com/55056403/151200026-59deb0cd-6c09-40a6-a3c8-ef84ad167e36.png)
![Screenshot from 2022-01-26 21-37-09](https://user-images.githubusercontent.com/55056403/151200459-73559303-9323-4bfe-9ac5-621789478d60.png)
