### ISSUE TITLE
Failed to inflate ColorStateList

### ISSUE THREAD

**Issue by elizacamber** [ittianyu/BottomNavigationViewEx#29]
I'm getting a crash after updating to android studio 3.0 preview 5
gradle url: `gradle-4.1-milestone-1-all.zip`
gradle tools: `com.android.tools.build:gradle:3.0.0-alpha5`
support libs: `26.0.0-beta2`
 
```
E/AppCompatResources: Failed to inflate ColorStateList, leaving it to the framework
                                                                         java.lang.IllegalArgumentException: alpha must be between 0 and 255.
                                                                             at android.support.v4.graphics.ColorUtils.setAlphaComponent(ColorUtils.java:298)
                                                                             at android.support.v7.content.res.AppCompatColorStateListInflater.modulateColorAlpha(AppCompatColorStateListInflater.java:169)
                                                                             at android.support.v7.content.res.AppCompatColorStateListInflater.inflate(AppCompatColorStateListInflater.java:144)
                                                                             at android.support.v7.content.res.AppCompatColorStateListInflater.createFromXmlInner(AppCompatColorStateListInflater.java:88)
                                                                             at android.support.v7.content.res.AppCompatColorStateListInflater.createFromXml(AppCompatColorStateListInflater.java:67)
                                                                             at android.support.v7.content.res.AppCompatResources.inflateColorStateList(AppCompatResources.java:116)
                                                                             at android.support.v7.content.res.AppCompatResources.getColorStateList(AppCompatResources.java:74)
                                                                             at android.support.design.widget.BottomNavigationView.createDefaultColorStateList(BottomNavigationView.java:399)
                                                                             at android.support.design.widget.BottomNavigationView.<init>(BottomNavigationView.java:147)
                                                                             at android.support.design.widget.BottomNavigationView.<init>(BottomNavigationView.java:114)
                                                                             at com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx.<init>(BottomNavigationViewEx.java:55)
                                                                             at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                             at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                             at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                             at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                             at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474)
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:155)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5696)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
android.view.InflateException: Binary XML file line #22: Error inflating class com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474)
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:155)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5696)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
                                                                      Caused by: android.view.InflateException: Binary XML file line #22: Error inflating class com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                         at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474) 
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:155) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5696) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823) 
                                                                      Caused by: java.lang.reflect.InvocationTargetException
                                                                         at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                         at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                         at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129) 
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364) 
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474) 
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:155) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5696) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823) 
                                                                      Caused by: java.lang.RuntimeException: Expecting menu, got ripple
                                                                         at android.support.v7.view.SupportMenuInflater.parseMenu(SupportMenuInflater.java:159)
                                                                         at android.support.v7.view.SupportMenuInflater.inflate(SupportMenuInflater.java:126)
                                                                         at android.support.design.widget.BottomNavigationView.inflateMenu(BottomNavigationView.java:234)
                                                                         at android.support.design.widget.BottomNavigationView.<init>(BottomNavigationView.java:165)
                                                                         at android.support.design.widget.BottomNavigationView.<init>(BottomNavigationView.java:114)
                                                                         at com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx.<init>(BottomNavigationViewEx.java:55)
                                                                         at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                         at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                         at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129) 
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364) 
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474) 
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:155) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5696) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

**Comment by ittianyu** [comment]
What is the color or xml content ?
I see the error message is "alpha must be between 0 and 255".
May be you have a wrong value of color.

**Comment by elizacamber** [comment]
It is working with the AS 3.0 Canary 4 and gradle tools `3.0.0-alpha4`

At the xml I only have the dimensions/paddings etc and this is my Java code but even when commented out I get the same errors. 

```
        mBottomNavigationView.setTextVisibility(false);
        mBottomNavigationView.enableShiftingMode(false);
        mBottomNavigationView.enableItemShiftingMode(false);
        // These parameters are provided in dps
        mBottomNavigationView.setIconSize(32, 32);
        try {
            @SuppressLint("ResourceType") XmlResourceParser parser = getResources().getXml(R.drawable.ic_nav_colors);
            ColorStateList colors = ColorStateList.createFromXml(getResources(), parser);
            for (int i = 0; i < mBottomNavigationView.getItemCount(); i++) {
                mBottomNavigationView.setIconTintList(i, colors);
            }
        } catch (XmlPullParserException | IOException e) {
            throw new IllegalStateException(e);
        }
```

**Comment by ittianyu** [comment]
You can use 
```
getResources().getColorStateList(R.drawable.ic_nav_colors)
```
to create a ColorStateList.
But I think you need use R.color.xxx instead of drawable.
You can see in demo.
The it is support selector in color.

**Comment by elizacamber** [comment]
Thnaks for the suggestion, I'll have a look. For now, I updated to 3.0 Canary 6  `tools.build:gradle:3.0.0-alpha6` and it works again without any changes
