### ISSUE TITLE
"No field mAnimationHelper" error is thrown in the console in version 26.0.0 of the design support lib

### ISSUE THREAD

**Issue by ddekanski** [ittianyu/BottomNavigationViewEx#39]
When running an app with design support 26.0.0, the following lengthy stacktrace shows up in the logcat:

```
W/System.err: java.lang.NoSuchFieldException: No field mAnimationHelper in class Landroid/support/design/internal/BottomNavigationMenuView; 
W/System.err:     at java.lang.Class.getDeclaredField(Native Method)
W/System.err:     at com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx.getField(BottomNavigationViewEx.java:799)
W/System.err:     at com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx.addAnimationListener(BottomNavigationViewEx.java:84)
W/System.err:     at com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx.init(BottomNavigationViewEx.java:70)
W/System.err:     at com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx.<init>(BottomNavigationViewEx.java:60)
W/System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)
W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:645)
W/System.err:     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
W/System.err:     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
W/System.err:     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
W/System.err:     at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:189)
W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:777)
W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
W/System.err:     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
W/System.err:     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
W/System.err:     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
W/System.err:     at no.rorbuer.eliassen.activities.BottomNavActivity_.setContentView(BottomNavActivity_.java:49)
W/System.err:     at no.rorbuer.eliassen.activities.BottomNavActivity_.onCreate(BottomNavActivity_.java:35)
W/System.err:     at android.app.Activity.performCreate(Activity.java:6679)
W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
W/System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:154)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
W/System.err:     at com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx.addAnimationListener(BottomNavigationViewEx.java:85)
W/System.err:     at com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx.init(BottomNavigationViewEx.java:70)
W/System.err:     at com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx.<init>(BottomNavigationViewEx.java:60)
W/System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)
W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:645)
W/System.err:     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
W/System.err:     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
W/System.err:     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
W/System.err:     at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:189)
W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:777)
W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
W/System.err:     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
W/System.err:     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
W/System.err:     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
W/System.err:     at no.rorbuer.eliassen.activities.BottomNavActivity_.setContentView(BottomNavActivity_.java:49)
W/System.err:     at no.rorbuer.eliassen.activities.BottomNavActivity_.onCreate(BottomNavActivity_.java:35)
W/System.err:     at android.app.Activity.performCreate(Activity.java:6679)
W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
W/System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:154)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by ittianyu** [comment]
Sorry. For some reason, I can't download version 26.0.0 even adding maven {url "https://maven.google.com"} with VPN.
So I recommend you use version 25.

**Comment by ittianyu** [comment]
But you can try the former version. It haven't use `mAnimationHelper`.
```
compile 'com.github.ittianyu:BottomNavigationViewEx:1.2.1'
```

**Comment by ittianyu** [comment]
I use 26.0.0 in version 1.2.3. Please try.

**Comment by shcoder1** [comment]
Hi @ittianyu! Could you please update Nuget package with this fix? Thanks for your work!
