### ISSUE TITLE
com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx.getFontHeight (Unknown Source:4)

### ISSUE THREAD

**Issue by pesjak** [ittianyu/BottomNavigationViewEx#52]
GREAT LIBRARY 👍,
but I have an issue... 
I'm testing the library in emulator works fine but on device i get this error:
com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx.getFontHeight (Unknown Source:4)

or full stack trace:

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.primoz.fluidwallpaper/com.primoz.fluidwallpaper.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6541)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
       at com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx.getFontHeight(Unknown Source:4)
       at com.primoz.fluidwallpaper.activities.MainActivity.onCreate(Unknown Source:49)
       at android.app.Activity.performCreate(Activity.java:6975)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6541)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

I'm using it like in onCreate:
```

ButterKnife.bind(this);

navigation.enableShiftingMode(false);
navigation.enableItemShiftingMode(false);
navigation.setTextVisibility(false); navigation.setOnNavigationItemSelectedListener(mOnNavigationItemSelectedListener);
```

**Comment by ittianyu** [comment]
What is your version of support lib.

**Comment by pesjak** [comment]
'com.android.support:support-v4:26.1.0'
'com.github.ittianyu:BottomNavigationViewEx:1.2.3'

**Comment by ittianyu** [comment]
Oh, you need keep support lib in same version.
Try 'com.android.support:support-v4:26.0.0'

**Comment by pesjak** [comment]
Now I'm getting:
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.0) from [com.android.support:preference-v7:26.0.0] AndroidManifest.xml:25:13-35
  	is also present at [com.android.support:design:26.0.1] AndroidManifest.xml:28:13-35 value=(26.0.1).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:23:9-25:38 to override.


My Manifest:

    <application
        android:name="MyApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_icon_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:roundIcon="@mipmap/ic_icon_launcher_round"
        android:theme="@style/AppTheme">
        <activity
            android:name="MainActivity"
            android:label="@string/app_name"
            android:theme="@style/AppTheme">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name="DetailsActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:label="@string/title_activity"
            android:theme="@style/AppTheme" />

        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.id"
            android:exported="false"
            android:grantUriPermissions="true"
            tools:replace="android:authorities" />

        <activity android:name="net.rdrei.android.dirchooser.DirectoryChooserActivity" />
        <activity
            android:name="SettingsActivity"
            android:label="@string/title_activity_settings"
            android:theme="@style/AppTheme" />
        <meta-data
            android:name="io.fabric.ApiKey"
            android:value="key" />
    </application>

**Comment by ittianyu** [comment]
You need check where has `com.android.support:design:26.0.1`.

If you can't find it.
try
```
    compile('com.github.ittianyu:BottomNavigationViewEx:1.2.3', {
        exclude group: 'com.android.support'
    })

```

**Comment by pesjak** [comment]
So i leave it like it is 26.1.0 and add exclude group: 'com.android.support'  to the library?

**Comment by ittianyu** [comment]
No, you project has 26.1.0 26.0.1 26.0.0 now. You can all use 26.0.1
