### ISSUE TITLE
Null pointer Exception

### ISSUE THREAD

**Issue by kushaljawa** [ittianyu/BottomNavigationViewEx#87]
IT is giving me this error  

FATAL EXCEPTION: main
                                                                              Process: com.example.kushal.instagram, PID: 14727
                                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.kushal.instagram/com.example.kushal.instagram.searchactivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx.enableAnimation(boolean)' on a null object reference
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                                                  at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                  at android.os.Looper.loop(Looper.java:164)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                               Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx.enableAnimation(boolean)' on a null object reference
                                                                                  at com.example.kushal.instagram.utils.BottomNavigationViewHelper.setupBottomNavigationView(BottomNavigationViewHelper.java:24)
                                                                                  at com.example.kushal.instagram.searchactivity.setupBottomNavigationView(searchactivity.java:31)
                                                                                  at com.example.kushal.instagram.searchactivity.onCreate(searchactivity.java:26)
                                                                                  at android.app.Activity.performCreate(Activity.java:6999)
                                                                                  at android.app.Activity.performCreate(Activity.java:6990)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
                                                                                  at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                  at android.os.Looper.loop(Looper.java:164) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
06-06 17:25:49.700 14727-14732/com.example.kushal.instagram I/zygote64: Compiler allocated 4MB to compile void android.view.View.<init>(android.content.Context, android.util.AttributeSet, int, int)

MY APP GRADLE
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.example.kushal.instagram"
        minSdkVersion 15
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:0.5'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    // coordinator library
    compile 'com.android.support:design:27.1.1'
    //bottom nav view
    compile 'com.github.ittianyu:BottomNavigationViewEx:1.2.4'
    compile'com.android.support:support-v4:27.1.1'

}

**Comment by Jitendra007Pawar** [comment]
same issue

**Comment by ittianyu** [comment]
I am sorry to be late. Please use version 2.0.0 if support lib >= 28.
For AndroidX, please add config into `gradle.properties`
```
android.useAndroidX=true
android.enableJetifier=true
```
