### ISSUE TITLE
Unable to resolve method setShiftingMode()

### ISSUE THREAD

**Issue by drianmr** [ittianyu/BottomNavigationViewEx#88]
Im getting this error:

java.lang.RuntimeException: Unable to start activity ComponentInfo{...activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2699)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6236)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx.enableShiftingMode(BottomNavigationViewEx.java:406)
        at ...activity.MainActivity.onCreate(MainActivity.kt:48)
        at android.app.Activity.performCreate(Activity.java:6684)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2652)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6236) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781) 

Support library version: 28.0.0-alpha1

![capture_9fe2f891ebf91c29](https://user-images.githubusercontent.com/25995656/41114100-a3033da6-6aad-11e8-9efe-371ef9d49be6.PNG)

**Comment by yusufceylan** [comment]
Same here, I get this error too with different methods like, enableAnimation, shiftingAnimation, enableItemShiftingMode

**Comment by btow** [comment]
A similar exception is thrown in the enableShiftingMode(boolean enable) method.

**Comment by btow** [comment]
A similar exception is thrown in the enableShiftingMode(boolean enable) method.

**Comment by fairytale110** [comment]
fixed  by me in #118

**Comment by ittianyu** [comment]
I am sorry to be late. Please use version 2.0.0 if support lib >= 28.
For AndroidX, please add config into `gradle.properties`
```
android.useAndroidX=true
android.enableJetifier=true
```
