### ISSUE TITLE
Binary XML file line #18: Error inflating class com.garazone.utility.BottomNavigationViewEx

### ISSUE THREAD

**Issue by hiteshsarsava** [ittianyu/BottomNavigationViewEx#91]
Caused by android.view.InflateException: Binary XML file line #18: Error inflating class com.garazone.utility.BottomNavigationViewEx
       at android.view.LayoutInflater.createView(LayoutInflater.java:623)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
       at com.garazone.home.HomeActivity.onCreate(HomeActivity.java:37)
       at android.app.Activity.performCreate(Activity.java:5242)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
       at android.app.ActivityThread.access$800(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5052)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by hiteshsarsava** [comment]
i used just a class of library and copy paste it in my project, getting error when checking in xiomi phone, android version 4.4 found this issue and getting crash

**Comment by JonathandelaSen** [comment]
Okay, so it was not a library. 
The problem came because I had my @menu/navigation under drawable-24 folder instead drawable folder. Really lame I know.

**Comment by subrud** [comment]
thanks. i also figured out the problem in my drawable folders

**Comment by ittianyu** [comment]
I am sorry to be late. Please use version 2.0.0 if support lib >= 28. 
Version 27 is abandoned.
For AndroidX, please add config into `gradle.properties`
```
android.useAndroidX=true
android.enableJetifier=true
```
